<table width="100%" cellpadding="0" cellspacing="0">
<tr bgcolor="#eeeeee"><td><h1>LoudBite.com</h1></td></tr>
<tr><td><a href="/">Home</a> | <a href="/AboutUs.html">About Us</a> | <a href="/account/new">Sign Up</a> | <a href="/artist/list-all-artists">View All Artists</a> | <a href="/artist/new">Add Artists</a> | <a href="/artist/store">My Store</a> | <a href="/account/logout">logout</a> | <a href="/account/accountmanager">My Loudbite Profile</a></td></tr>
</table>


<br />
