<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
   <?php echo $this->headTitle('LoudBite.com - Amazon test'); ?>
</head>
<body>

    <?php echo $this->render('includes/header.phtml') ?>
    <h3>Amazon Sorting test</h3>
	<?php
	foreach($this->results as $result)
	{
		echo $result->Title."<br>";
	}

    echo "<br>";
    echo "Total Books: ".$this->results->totalResults();
    echo "<br>";
    echo "Total Pages: ".$this->results->totalPages();


	?>
</body>
</html>
